version: '3'

services:
  api:
    build: .docker/api
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s /entrypoint.sh
    container_name: imersao-fullcycle-3-desafio2-api
    ports:
      - 3000:3000
    volumes:
      - ./api:/home/node/app
      - ./.docker/api/entrypoint.sh:/entrypoint.sh
    depends_on: 
      - db
  next:
    build: .docker/next
    entrypoint: dockerize -wait tcp://api:3000 -timeout 40s /entrypoint.sh
    container_name: imersao-fullcycle-3-desafio2-next
    ports:
      - 3001:3000
    volumes:
      - ./next:/home/node/app
      - ./.docker/next/entrypoint.sh:/entrypoint.sh
    depends_on: 
      - db
  db:
    build: .docker/postgres
    container_name: imersao-fullcycle-3-desafio2-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=routes

  pgadmin:
    image: dpage/pgadmin4
    container_name: imersao-fullcycle-3-desafio2-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80