apiVersion: apps/v1
kind: Deployment
metadata:
  name: imersao-fullcycle-3-desafio-2-api
spec:
  selector:
    matchLabels:
      app: imersao-fullcycle-3-desafio-2-api
  replicas: 1
  template:
    metadata:
      labels:
        app: imersao-fullcycle-3-desafio-2-api
    spec:
      containers:
        - name: imersao-fullcycle-3-desafio-2-api
          image: jlohn/imersao-fullcycle-3-desafio-2-api
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          env:
          - name: "TYPEORM_CONNECTION"
            value: "postgres"
          - name: "TYPEORM_HOST"
            value: "imersao-fullcycle-3-desafio-2-db"
          - name: "TYPEORM_USERNAME"
            value: "postgres"
          - name: "TYPEORM_PASSWORD"
            value: "root"
          - name: "TYPEORM_DATABASE"
            value: "app"
          - name: "TYPEORM_PORT"
            value: "5432"
          - name: "TYPEORM_ENTITIES"
            value: "dist/**/*.entity.js"
          - name: "TYPEORM_ENTITIES_DIR"
            value: "src"
          - name: "TYPEORM_MIGRATIONS"
            value: "src/migrations/*.ts"
          - name: "TYPEORM_MIGRATIONS_DIR"
            value: "src/migrations"
          - name: "TZ"
            value: "America/Sao_Paulo"
---
kind: Service
apiVersion: v1
metadata:
  name: imersao-fullcycle-3-desafio-2-api
spec:
  selector:
    app: imersao-fullcycle-3-desafio-2-api
  ports:
    - port: 3000
  type: ClusterIP
