import {
    Card,
    CardMedia,
    CardContent,
    CardActions,
    Typography,
    Button,
    Grid,
} from "@material-ui/core";
import Head from "next/head";
import { Route } from "../model";
import { GetServerSideProps, NextPage } from "next";
import http from "../http";

interface RoutesListPageProps {
    routes: Route[];
}

const RoutesListPage: NextPage<RoutesListPageProps> = ({ routes }) => {
    return (
        <div>
            <Head>
                <title>Listagem de rotas</title>
                {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <Typography component="h1" variant="h3" color="textPrimary" gutterBottom>
                Rotas
            </Typography>
            <Grid container spacing={4}>
                {routes.map((product, key) => (
                    <Grid key={key} item xs={12} sm={6} md={4}>
                        <Card>
                            <CardContent>
                                <Typography component="h2" variant="h5" gutterBottom>
                                    {product.title}
                                </Typography>
                                <Typography component="h4" variant="h5" gutterBottom>
                                    Start: {product.startPosition} <br />
                                    End: {product.endPosition}
                                </Typography>
                            </CardContent>
                        </Card>
                    </Grid>
                ))}
            </Grid>
        </div>
    );
};

export default RoutesListPage;

export const getServerSideProps: GetServerSideProps<RoutesListPageProps> = async (context) => {
    const { data: routes } = await http.get("routes");
    console.log(routes);
    return {
        props: {
            routes,
        },
    };
};
